runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: website/www/index.html
  upload: website/www/index.html

- url: /(.*)
  static_files: www/\1
  upload: website/www/(.*)